[tool.poetry]
name = "Times Tables In Python"
version = "0.1.0"
description = ""
authors = ["Logan Connors loganconnors186@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"